// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgIIrId2x72DZ2dtJ1RrVtirabhx2SaJ8',
    appId: '1:1097036028807:web:6ac57025df30021ed11122',
    messagingSenderId: '1097036028807',
    projectId: 'it5-teamj1',
    authDomain: 'it5-teamj1.firebaseapp.com',
    storageBucket: 'it5-teamj1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChdNiHaCjluqxEzMXkhmZs44vXTDUfdmI',
    appId: '1:1097036028807:android:f1dffcaf3769f2edd11122',
    messagingSenderId: '1097036028807',
    projectId: 'it5-teamj1',
    storageBucket: 'it5-teamj1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAquG7cTKu9OXLfMLLjyT1Pzu4z5gbh1_I',
    appId: '1:1097036028807:ios:e258ddcebdcd8f9ad11122',
    messagingSenderId: '1097036028807',
    projectId: 'it5-teamj1',
    storageBucket: 'it5-teamj1.firebasestorage.app',
    iosClientId: '1097036028807-i8l7gqt9gft9t53k164r23glk35qfkth.apps.googleusercontent.com',
    iosBundleId: 'com.example.univentsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAquG7cTKu9OXLfMLLjyT1Pzu4z5gbh1_I',
    appId: '1:1097036028807:ios:e258ddcebdcd8f9ad11122',
    messagingSenderId: '1097036028807',
    projectId: 'it5-teamj1',
    storageBucket: 'it5-teamj1.firebasestorage.app',
    iosClientId: '1097036028807-i8l7gqt9gft9t53k164r23glk35qfkth.apps.googleusercontent.com',
    iosBundleId: 'com.example.univentsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgIIrId2x72DZ2dtJ1RrVtirabhx2SaJ8',
    appId: '1:1097036028807:web:14ffbc62c48f6a72d11122',
    messagingSenderId: '1097036028807',
    projectId: 'it5-teamj1',
    authDomain: 'it5-teamj1.firebaseapp.com',
    storageBucket: 'it5-teamj1.firebasestorage.app',
  );

}