// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgIIrId2x72DZ2dtJ1RrVtirabhx2SaJ8',
    appId: '1:1097036028807:web:6ac57025df30021ed11122',
    messagingSenderId: '1097036028807',
    projectId: 'it5-teamj1',
    authDomain: 'it5-teamj1.firebaseapp.com',
    storageBucket: 'it5-teamj1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChdNiHaCjluqxEzMXkhmZs44vXTDUfdmI',
    appId: '1:1097036028807:android:fcf925bf90f949c5d11122',
    messagingSenderId: '1097036028807',
    projectId: 'it5-teamj1',
    storageBucket: 'it5-teamj1.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAquG7cTKu9OXLfMLLjyT1Pzu4z5gbh1_I',
    appId: '1:1097036028807:ios:8fd3de8f010e565dd11122',
    messagingSenderId: '1097036028807',
    projectId: 'it5-teamj1',
    storageBucket: 'it5-teamj1.firebasestorage.app',
    androidClientId: '1097036028807-bnfbphpalhv27va7t1iq93sqhih0fe6a.apps.googleusercontent.com',
    iosClientId: '1097036028807-89gjlunbds32he7kl7re2m42h8revemo.apps.googleusercontent.com',
    iosBundleId: 'com.clarknotkent.univents',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAquG7cTKu9OXLfMLLjyT1Pzu4z5gbh1_I',
    appId: '1:1097036028807:ios:8fd3de8f010e565dd11122',
    messagingSenderId: '1097036028807',
    projectId: 'it5-teamj1',
    storageBucket: 'it5-teamj1.firebasestorage.app',
    androidClientId: '1097036028807-bnfbphpalhv27va7t1iq93sqhih0fe6a.apps.googleusercontent.com',
    iosClientId: '1097036028807-89gjlunbds32he7kl7re2m42h8revemo.apps.googleusercontent.com',
    iosBundleId: 'com.clarknotkent.univents',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgIIrId2x72DZ2dtJ1RrVtirabhx2SaJ8',
    appId: '1:1097036028807:web:14ffbc62c48f6a72d11122',
    messagingSenderId: '1097036028807',
    projectId: 'it5-teamj1',
    authDomain: 'it5-teamj1.firebaseapp.com',
    storageBucket: 'it5-teamj1.firebasestorage.app',
  );

}
