// lib/main.dart
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI

// Import screen files
import 'splash_screen.dart';
import 'login_screen.dart';
import 'home_screen.dart'; // Import the separate home screen file

// Main entry point of the application
void main() async {
  // Ensure Flutter bindings are initialized before Firebase
  WidgetsFlutterBinding.ensureInitialized();
  // Initialize Firebase using platform-specific options
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  // Run the root application widget
  runApp(const MyApp());
}

// Root application widget
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      // App title
      title: 'UNIVENTS!',
      // App theme configuration
      theme: ThemeData(
        primarySwatch: Colors.blue, // Base theme color
        visualDensity: VisualDensity.adaptivePlatformDensity, // Adjust density based on platform
        // You can define fonts, colors, etc., here
        // fontFamily: 'SpectralSC', // Example custom font
      ),
      // Hide the debug banner in the top-right corner
      debugShowCheckedModeBanner: false,
      // The initial route to display when the app starts
      initialRoute: '/splash',
      // Define the named routes for navigation within the app
      routes: {
        // Route for the splash screen
        '/splash': (context) => const SplashScreen(),
        // Route for the login screen
        '/login': (context) => const LoginScreen(),
        // Route for the home screen (uses the imported HomeScreen widget)
        '/home': (context) => const HomeScreen(),
      },
    );
  }
}
